
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CfgAssetPath
{
    private readonly System.Collections.Generic.Dictionary<EnumAudioClip, AssetPath> _dataMap;
    private readonly System.Collections.Generic.List<AssetPath> _dataList;
    
    public CfgAssetPath(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<EnumAudioClip, AssetPath>();
        _dataList = new System.Collections.Generic.List<AssetPath>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            AssetPath _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = AssetPath.DeserializeAssetPath(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EnumName, _v);
        }
    }

    public System.Collections.Generic.Dictionary<EnumAudioClip, AssetPath> DataMap => _dataMap;
    public System.Collections.Generic.List<AssetPath> DataList => _dataList;

    public AssetPath GetOrDefault(EnumAudioClip key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AssetPath Get(EnumAudioClip key) => _dataMap[key];
    public AssetPath this[EnumAudioClip key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

