
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EnumAudioClip
    {
        None = 0,
        /// <summary>
        /// 打字
        /// </summary>
        A1 = 1,
        /// <summary>
        /// 主角移动
        /// </summary>
        A16 = 2,
        /// <summary>
        /// 主角受击
        /// </summary>
        A17 = 3,
    }

} 

