
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EnumAudioClip
    {
        None = 0,
        A1 = 1,
        主角移动 = 2,
        主角受击 = 3,
        主角休息 = 4,
        使用物品 = 5,
        关闭Esc界面 = 6,
        切换Esc界面栏 = 7,
        切换物品位置 = 8,
        存档成功 = 9,
        开门 = 10,
        打开Esc界面 = 11,
        普通点击 = 12,
        火堆界面 = 13,
        行走 = 14,
        跳跃 = 15,
        采摘 = 16,
        BGM = 17,
    }

} 

