
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EnumAudioClip
    {
        None = 0,
        A1 = 1,
        主角移动 = 2,
        主角受击 = 3,
    }

} 

